#!/usr/bin/env bash
# Build full offline doc tree on the USB project folder (32 GB OK).
# - Keeps hand notes in docs/
# - Mirrors upstream GoClaw markdown docs into docs/mirrors/goclaw/
# - Optional: chip-docs-local tool into skills/vendor for more mirrors later
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
mkdir -p docs/mirrors docs/custom

GOCLAW_DOCS_DIR="docs/mirrors/goclaw"
GOCLAW_REPO_URL="${GOCLAW_REPO_URL:-https://github.com/nextlevelbuilder/goclaw.git}"
GOCLAW_REF="${GOCLAW_REF:-dev}"

log() { echo "==> $*"; }

# --- GoClaw official markdown docs (sparse) ---
fetch_goclaw_docs() {
  if [[ -d "$GOCLAW_DOCS_DIR/.git" ]] || [[ -f "$GOCLAW_DOCS_DIR/README.md" && -d "$GOCLAW_DOCS_DIR/docs" ]]; then
    log "GoClaw docs mirror present: $GOCLAW_DOCS_DIR"
    if [[ -d "$GOCLAW_DOCS_DIR/.git" ]]; then
      git -C "$GOCLAW_DOCS_DIR" fetch --depth 1 origin "$GOCLAW_REF" 2>/dev/null || true
      git -C "$GOCLAW_DOCS_DIR" checkout "FETCH_HEAD" -- docs README.md 2>/dev/null || true
    fi
    return 0
  fi

  log "Cloning GoClaw docs (sparse) → $GOCLAW_DOCS_DIR"
  tmp="$(mktemp -d)"
  git clone --depth 1 --filter=blob:none --sparse -b "$GOCLAW_REF" "$GOCLAW_REPO_URL" "$tmp/goclaw"
  git -C "$tmp/goclaw" sparse-checkout set docs README.md _readmes 2>/dev/null \
    || git -C "$tmp/goclaw" sparse-checkout set docs README.md
  rm -rf "$GOCLAW_DOCS_DIR"
  mkdir -p "$GOCLAW_DOCS_DIR"
  # copy tracked content
  if [[ -d "$tmp/goclaw/docs" ]]; then
    cp -a "$tmp/goclaw/docs" "$GOCLAW_DOCS_DIR/"
  fi
  [[ -f "$tmp/goclaw/README.md" ]] && cp -a "$tmp/goclaw/README.md" "$GOCLAW_DOCS_DIR/"
  [[ -d "$tmp/goclaw/_readmes" ]] && cp -a "$tmp/goclaw/_readmes" "$GOCLAW_DOCS_DIR/"
  rm -rf "$tmp"
  log "GoClaw offline docs ready: $GOCLAW_DOCS_DIR"
}

write_index() {
  local idx="docs/FILELIST.md"
  log "Writing $idx"
  {
    echo "# Offline docs index"
    echo
    echo "Generated by scripts/fetch-offline-docs.sh"
    echo
    echo "## Hand-maintained"
    find docs -maxdepth 2 -type f -name '*.md' ! -path 'docs/mirrors/*' 2>/dev/null | sort | sed 's|^|- |'
    echo
    echo "## Mirrors"
    find docs/mirrors -type f -name '*.md' 2>/dev/null | sort | sed 's|^|- |' || echo "- (none yet)"
  } > "$idx"
}

fetch_goclaw_docs
write_index

log "Optional next: bash scripts/fetch-human20-skill.sh chip-docs-local"
log "Then use chip-docs-local to mirror more public sites into docs/mirrors/"
log "Done."
